[project]
name = "azure-tagday-ui"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "jinja2>=3.1.6",
    "pyside6>=6.11.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
gui = "gui.main:main"
tagday-gui = "gui.main:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"gui" = ["qml/*.qml", "qml/**/*.qml"]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]

